### listar almacen
GET http://127.0.0.1:3000/almacen


### guardar almacen

POST http://127.0.0.1:3000/almacen
Content-Type: application/json

{
    "nombre": "almacen 002",
    "codigo": "alm-002",
    "descripcion": "almacen central",
    "sucursal": 16
}

### mostrar almacen

GET http://127.0.0.1:3000/almacen/3

### modificar almacen

PATCH  http://127.0.0.1:3000/almacen/1
Content-Type: application/json

{
    "nombre": "muebles para oficina",
    "descripcion": "de madera"
}
### eliminar categoria // no deberiamos de eliminar, seria bueno cambios de estados o eliminacion temporal para recuperar despues por temas de auditoria no deberiamos de eliminar
DELETE http://127.0.0.1:3000/categoria/2
