### login
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "email": "anit@mail.com",
    "password": "anit1234"
}

### registro de usuario

POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "username": "simon10",
    "email": "simon@mail.com",
    "password": "simon123"
}

### perfil, debemos proteger esta ruta, nadie podria acceder si no estan autenticados, podemos crear un decorados guards controlara si es correcto el token, hay diferentes guards
GET http://127.0.0.1:3000/auth/profile
Authorization: Berear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRjOGRjNjAwLWE5M2EtNDQ2YS1iZDcxLWFhNTI5NzIwYTU3NSIsInVzZXJuYW1lIjoiYW5pdGwyIiwiaWF0IjoxNzUzNTY0MDEzLCJleHAiOjE3NTM1Njc2MTN9.S0GCQSmbkkH-Ln1JoPrm0FVy_-fHw9gYcs9UC62PnS0