GET http://127.0.0.1:3000/nota?tipo_nota=ingreso&desde=2025-06-01&hasta=2025-06-12&entidad_comercial_id=2&limit=1&page=3

### guardar nota ingreso

POST http://127.0.0.1:3000/nota
Content-Type: application/json
Accept: application/json

{
    "codigo_nota": "n017",
    "fecha_emision": "2025-07-01",
    "tipo_nota": "compra",
    "entidad_comercial_id": 2,
    "user_id": "2d0cb5b9-3117-48d7-ab09-12cefb5907fa",
    "total_calculado": "210.90",
    "estado_nota": "emitido",
    "movimientos": [
        {
            "producto_id": 7,
            "almacen_id": 1,
            "cantidad": 5,
            "tipo_movimientos": "ingreso",
            "precio_unitario_compra": 3,
            "precio_unitario_venta": 5,
            "total_linea": 100,
            "observaciones": "nueva combra 2 b"
        }
    ]

}


### guardar nota salida

POST http://127.0.0.1:3000/nota
Content-Type: application/json
Accept: application/json

{
    "codigo_nota": "n021",
    "fecha_emision": "2025-06-12",
    "tipo_nota": "ingreso",
    "entidad_comercial_id": 3,
    "user_id": "2d0cb5b9-3117-48d7-ab09-12cefb5907fa",
    "subtotal": "50.00",
    "impuestos":"6.5",
    "descuento_total": "0.00",
    "total_calculado": "120.90",
    "estado_nota": "emitido",
    "observaciones": "venta parcial",
    "movimientos": [
        {
            "producto_id": 40,
            "almacen_id": 1,
            "cantidad": 30,
            "tipo_movimientos": "ingreso",
            "precio_unitario_compra": 2,
            "precio_unitario_venta": 5,
            "total_linea": 100,
            "observaciones": "nueva compra producto"
        }

    ]



}



### mostrar nota

GET http://127.0.0.1:3000/nota/9