GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRjOGRjNjAwLWE5M2EtNDQ2YS1iZDcxLWFhNTI5NzIwYTU3NSIsInVzZXJuYW1lIjoiYW5pdGwyIiwiaWF0IjoxNzUxMzExMzE4LCJleHAiOjE3NTEzMTQ5MTh9.w8do4nmof1whMdcseDfaL2MOFzCM2WW7oaWiq5lEOYE

### guardar usuarios

POST http://127.0.0.1:3000/users
Content-Type: application/json

{
    "username": "anitl2",
    "email": "anit@mail.com",
    "password": "anit1234"
}

### mostrar un usuario por id
GET http://127.0.0.1:3000/users/10e699cf-7e7e-4d3f-a7fb-fb82dff11551

### modificar un usuario
PATCH http://127.0.0.1:3000/users/10e699cf-7e7e-4d3f-a7fb-fb82dff11551
Content-Type: application/json

{
  "username": "juan.modificado",
  "email": "juanmodifi@mail.com"
}
### eliminar
DELETE http://127.0.0.1:3000/users/1099dc42-0035-4f59-b831-7700ff1393b6


### crear usuario con roles

POST http://127.0.0.1:3000/users
Content-Type: application/json

{
    "username": "an222ppl2",
    "email": "an222pp2@mail.com",
    "password": "pplooo221234",
    "roleIds":["0f01bc44-06be-4768-b640-148cd8317f0e", "b5473e9a-a18d-480e-b9d5-53d297133cca"]
}